import app from "../assests/images/app.png"
import fb from "../assests/images/fb.png"
import insta from "../assests/images/insta.png"
import logo from "../assests/images/logo.png"
import phone from "../assests/images/phone.png"
import Search from "../assests/images/Search.png"
import yt from "../assests/images/yt.png"
import abouta from "../assests/images/abouta.png"
import aboutb from "../assests/images/aboutb.png"
import aboutc from "../assests/images/aboutc.png"
import aboutd from "../assests/images/aboutd.png"
import slick from '../assests/images/slick.png'
import slick1 from '../assests/images/slick1.png'
import slick2 from '../assests/images/slick2.png'
import slick3 from '../assests/images/slick3.png'
import slick4 from '../assests/images/slick4.png'
import photo from '../assests/images/photo.png'
import photo1 from '../assests/images/photo1.png'
import photo2 from '../assests/images/photo2.png'
import photo3 from '../assests/images/photo3.png'
import photo4 from '../assests/images/photo4.png'
import achieve from '../assests/images/achieve.png'
import achieve1 from '../assests/images/achieve1.png'
import achieve2 from '../assests/images/achieve2.png'
import achieve3 from '../assests/images/achieve3.png'
import achieve4 from '../assests/images/achieve4.png'
import image404 from '../assests/images/image 404.png'
import birth from '../assests/images/birth.png'
import birth1 from '../assests/images/birth1.png'
import birth2 from '../assests/images/birth2.png'
import birth3 from '../assests/images/birth3.png'
import dajt from '../assests/images/dajt.png'
import museum from '../assests/images/museum.png'
import museum1 from '../assests/images/museum1.png'
import museum2 from '../assests/images/museum2.png'
import museum3 from '../assests/images/museum3.png'
import museum4 from '../assests/images/museum4.png'
import museum5 from '../assests/images/museum5.png'
import museum6 from '../assests/images/museum6.png'
import museum7 from '../assests/images/museum7.png'
import book1 from './images/book1.png'
import contact from './images/contact.png'
import contact1 from './images/contact1.png'
import contact3 from './images/contact3.png'
import mapping from './images/mapping.jpeg'
export {app,fb,insta,logo,phone,Search,yt,abouta,aboutb,aboutc,aboutd,slick,slick1,slick2,slick3,slick4,photo,photo1,photo2,photo3,photo4,achieve,achieve1,achieve2,achieve3,achieve4,image404,birth,birth1,birth2,birth3,dajt,museum,museum2,museum1,museum3,museum4,museum5,museum6,museum7,book1,contact,contact1,contact3,mapping }